# Generated by Django 3.0.5 on 2020-04-06 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_subsctibers', '0002_auto_20200406_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_subsctibers.Subscriber')),
                ('user_subsciber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subsciber_user_id', to='get_subsctibers.Subscriber')),
            ],
        ),
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
